{
 "title": "App Monitoring",
 "description": "Application monitoring metrics",
 "tags": [
  "app",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 } },
  {
   "title": "Total Orders",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orders_total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "app"
    }
   ]
  },
  {
   "title": "Orders Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "orders_rate",
     "expr": "rate(orders_total[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "orders per second",
     "measurement": "app"
    }
   ]
  },
  {
   "title": "PostgreSQL Connection",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_connection_status{db=\"postgres\"}"
    }
   ]
  },
  {
   "title": "Redis Connection",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_connection_status{db=\"redis\"}"
    }
   ]
  }
 ]
}