from typing import TypeVar, Protocol
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import DeclarativeBase

T = TypeVar('T', bound=DeclarativeBase)

class IRepository(Protocol[T]):
    """Базовый интерфейс репозитория"""
    async def get_by_id(self, id: int) -> T | None: ...
    async def get_all(self, limit: int = 100, offset: int = 0) -> list[T]: ...
    async def create(self, **kwargs) -> T: ...
    async def update(self, id: int, **kwargs) -> T | None: ...
    async def delete(self, id: int) -> bool: ...

class IUnitOfWork(Protocol):
    """Интерфейс Unit of Work"""
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def __aenter__(self) -> "IUnitOfWork": ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...